### ISSUE TITLE
dplyr and operators error

### ISSUE THREAD

**Issue by AdamMJenks** [romainfrancois/operators#4]
When dplyr version 0.5.0 and operators version 0.1.8 are both loaded packages, the following line throws and error.

```
iris %>% group_by(Species) %>% summarise(A = n())
```

yields the following error:

```
Error in summarise_(.data, .dots = lazyeval::lazy_dots(...)) : 
  argument ".data" is missing, with no default
```

session info:
```
R version 3.3.0 (2016-05-03)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.10.3 (Yosemite)

```

**Comment by romainfrancois** [comment]
I guess `operators` should find another operator than `%>%` for redirection to files. 
https://github.com/romainfrancois/operators/blob/master/R/file.R#L37

**Comment by AdamMJenks** [comment]
Yeah, it overrules the piping functionality of dplyr.  I'd suggest something like `%file>%`, do you want me to make a pull request and alter the code?

**Comment by romainfrancois** [comment]
That's fine by me, esp that I don't think this pkg is being used a lot. 
Would you work on a PR ?

**Comment by AdamMJenks** [comment]
Just made the pull request, simple changes to the `%>%` and `%>>%` operators to keep the syntax consistent
